#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config focus_follows_pointer true 

bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config top_padding          48
bspc config bottom_padding       32
bspc config left_padding         32
bspc config right_padding        32

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a discord desktop='^3' follow=off fullscreen=on
bspc rule -a spotify desktop='^4' follow=off fullscreen=on

sh $HOME/.config/polybar/launch.sh &
