#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config focus_follows_pointer true 

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a discord desktop='^3' follow=off fullscreen=on
bspc rule -a spotify desktop='^4' follow=off fullscreen=on

sh $HOME/.config/polybar/launch.sh &
